version: "3.9"
services:

  db:
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
      - POSTGRES_PASSWORD=postgres
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
