"""autogenerate

Revision ID: 5c0dfaff4d79
Revises: 4aaf88d14d9d
Create Date: 2021-06-27 13:00:38.070789

"""
from alembic import op
import sqlalchemy as sa

import app


# revision identifiers, used by Alembic.
revision = '5c0dfaff4d79'
down_revision = '4aaf88d14d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('on_air_schedules', sa.Column('created_at', app.models.types.DateTime(timezone=True), nullable=True))
    op.add_column('on_air_schedules', sa.Column('updated_at', app.models.types.DateTime(timezone=True), nullable=True))
    op.add_column('on_air_schedules', sa.Column('title', sa.Text(), nullable=False))
    op.add_column('on_air_schedules', sa.Column('episode', sa.Text(), nullable=False))
    op.add_column('on_air_schedules', sa.Column('start', app.models.types.DateTime(timezone=True), nullable=False))
    op.add_column('on_air_schedules', sa.Column('end', app.models.types.DateTime(timezone=True), nullable=False))
    op.add_column('on_air_schedules', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('on_air_schedules', 'version')
    op.drop_column('on_air_schedules', 'end')
    op.drop_column('on_air_schedules', 'start')
    op.drop_column('on_air_schedules', 'episode')
    op.drop_column('on_air_schedules', 'title')
    op.drop_column('on_air_schedules', 'updated_at')
    op.drop_column('on_air_schedules', 'created_at')
    # ### end Alembic commands ###
